#pragma once
#include "../vm.h"

void register_all_builtins(VM* vm);
SapphireValue native_lru_create(int arg_count, SapphireValue* args);
SapphireValue native_lru_has(int arg_count, SapphireValue* args);
SapphireValue native_lru_get(int arg_count, SapphireValue* args);
SapphireValue native_lru_put(int arg_count, SapphireValue* args);
SapphireValue native_value_to_string(int arg_count, SapphireValue* args);
SapphireValue native_len(int arg_count, SapphireValue* args);
SapphireValue native_evaluate(int arg_count, SapphireValue* args);
SapphireValue native_debug_print_stack(int arg_count, SapphireValue* args);
SapphireValue native_debug_dump_globals(int arg_count, SapphireValue* args);
SapphireValue native_get_quote(int arg_count, SapphireValue* args);
SapphireValue native_color_hex_to_rgb(int arg_count, SapphireValue* args);
SapphireValue native_check_collision(int arg_count, SapphireValue* args);
SapphireValue native_http_get(int arg_count, SapphireValue* args);
SapphireValue native_http_ping(int arg_count, SapphireValue* args);
SapphireValue native_http_post(int arg_count, SapphireValue* args);
SapphireValue native_http_download(int arg_count, SapphireValue* args);
SapphireValue native_http_get_full(int arg_count, SapphireValue* args);
SapphireValue native_http_post_full(int arg_count, SapphireValue* args);
SapphireValue native_http_put_full(int arg_count, SapphireValue* args);
SapphireValue native_http_delete_full(int arg_count, SapphireValue* args);
SapphireValue native_http_serve(int arg_count, SapphireValue* args);
SapphireValue native_io_write_file(int arg_count, SapphireValue* args);
SapphireValue native_io_read_file(int arg_count, SapphireValue* args);
SapphireValue native_io_open_file_dialog(int arg_count, SapphireValue* args);
SapphireValue native_io_file_size(int arg_count, SapphireValue* args);
SapphireValue native_io_is_dir(int arg_count, SapphireValue* args);
SapphireValue native_io_exists(int arg_count, SapphireValue* args);
SapphireValue native_io_print_color(int arg_count, SapphireValue* args);
SapphireValue native_io_read_input(int arg_count, SapphireValue* args);
SapphireValue native_io_delete_file(int arg_count, SapphireValue* args);
SapphireValue native_io_append_file(int arg_count, SapphireValue* args);
// NEW in v1.0.9 — Advanced IO
SapphireValue native_io_list_dir(int arg_count, SapphireValue* args);
SapphireValue native_io_list_dir_recursive(int arg_count, SapphireValue* args);
SapphireValue native_io_copy_file(int arg_count, SapphireValue* args);
SapphireValue native_io_move_file(int arg_count, SapphireValue* args);
SapphireValue native_io_rename(int arg_count, SapphireValue* args);
SapphireValue native_io_make_dir(int arg_count, SapphireValue* args);
SapphireValue native_io_make_all_dirs(int arg_count, SapphireValue* args);
SapphireValue native_io_get_temp_dir(int arg_count, SapphireValue* args);
SapphireValue native_io_read_lines(int arg_count, SapphireValue* args);
SapphireValue native_io_read_binary(int arg_count, SapphireValue* args);
SapphireValue native_io_write_binary(int arg_count, SapphireValue* args);
SapphireValue native_io_get_absolute_path(int arg_count, SapphireValue* args);
SapphireValue native_io_get_parent_dir(int arg_count, SapphireValue* args);
SapphireValue native_io_get_extension(int arg_count, SapphireValue* args);
SapphireValue native_io_get_basename(int arg_count, SapphireValue* args);
SapphireValue native_io_is_file(int arg_count, SapphireValue* args);
// NEW in v1.0.9 — Crypto module
SapphireValue native_crypto_sha256(int arg_count, SapphireValue* args);
SapphireValue native_crypto_sha1(int arg_count, SapphireValue* args);
SapphireValue native_crypto_md5(int arg_count, SapphireValue* args);
SapphireValue native_crypto_hmac_sha256(int arg_count, SapphireValue* args);
SapphireValue native_crypto_base64_encode(int arg_count, SapphireValue* args);
SapphireValue native_crypto_base64_decode(int arg_count, SapphireValue* args);
SapphireValue native_crypto_random_bytes(int arg_count, SapphireValue* args);
SapphireValue native_crypto_random_hex(int arg_count, SapphireValue* args);
SapphireValue native_crypto_uuid4(int arg_count, SapphireValue* args);
SapphireValue native_crypto_aes_encrypt(int arg_count, SapphireValue* args);
SapphireValue native_crypto_aes_decrypt(int arg_count, SapphireValue* args);
// NEW in v1.0.9 — Net module
SapphireValue native_net_tcp_connect(int arg_count, SapphireValue* args);
SapphireValue native_net_tcp_send(int arg_count, SapphireValue* args);
SapphireValue native_net_tcp_receive(int arg_count, SapphireValue* args);
SapphireValue native_net_tcp_close(int arg_count, SapphireValue* args);
SapphireValue native_net_resolve(int arg_count, SapphireValue* args);
SapphireValue native_net_local_ip(int arg_count, SapphireValue* args);
SapphireValue native_net_is_port_open(int arg_count, SapphireValue* args);

SapphireValue native_json_parse(int arg_count, SapphireValue* args);
SapphireValue native_json_stringify(int arg_count, SapphireValue* args);
SapphireValue native_list_util_reverse(int arg_count, SapphireValue* args);
SapphireValue native_list_util_clear(int arg_count, SapphireValue* args);
SapphireValue native_list_util_index_of(int arg_count, SapphireValue* args);
SapphireValue native_list_util_join(int arg_count, SapphireValue* args);
SapphireValue native_list_util_create(int arg_count, SapphireValue* args);
SapphireValue native_list_util_append(int arg_count, SapphireValue* args);
SapphireValue native_list_util_get(int arg_count, SapphireValue* args);
SapphireValue native_list_util_set(int arg_count, SapphireValue* args);
SapphireValue native_list_util_length(int arg_count, SapphireValue* args);
SapphireValue native_list_util_remove_at(int arg_count, SapphireValue* args);
SapphireValue native_list_util_contains(int arg_count, SapphireValue* args);
SapphireValue native_map_keys(int arg_count, SapphireValue* args);
SapphireValue native_map_values(int arg_count, SapphireValue* args);
SapphireValue native_map_has(int arg_count, SapphireValue* args);
SapphireValue native_map_remove(int arg_count, SapphireValue* args);
SapphireValue native_math_tan(int arg_count, SapphireValue* args);
SapphireValue native_math_asin(int arg_count, SapphireValue* args);
SapphireValue native_math_acos(int arg_count, SapphireValue* args);
SapphireValue native_math_atan(int arg_count, SapphireValue* args);
SapphireValue native_math_atan2(int arg_count, SapphireValue* args);
SapphireValue native_math_sinh(int arg_count, SapphireValue* args);
SapphireValue native_math_cosh(int arg_count, SapphireValue* args);
SapphireValue native_math_tanh(int arg_count, SapphireValue* args);
SapphireValue native_math_exp(int arg_count, SapphireValue* args);
SapphireValue native_math_log10(int arg_count, SapphireValue* args);
SapphireValue native_math_trunc(int arg_count, SapphireValue* args);
SapphireValue native_math_round(int arg_count, SapphireValue* args);
SapphireValue native_math_sqrt(int arg_count, SapphireValue* args);
SapphireValue native_math_rand(int arg_count, SapphireValue* args);
SapphireValue native_math_abs(int arg_count, SapphireValue* args);
SapphireValue native_math_floor(int arg_count, SapphireValue* args);
SapphireValue native_math_ceil(int arg_count, SapphireValue* args);
SapphireValue native_math_sin(int arg_count, SapphireValue* args);
SapphireValue native_math_cos(int arg_count, SapphireValue* args);
SapphireValue native_math_log(int arg_count, SapphireValue* args);
SapphireValue native_math_pow(int arg_count, SapphireValue* args);
SapphireValue native_math_min(int arg_count, SapphireValue* args);
SapphireValue native_math_max(int arg_count, SapphireValue* args);
SapphireValue native_math_clamp(int arg_count, SapphireValue* args);
SapphireValue native_math_lerp(int arg_count, SapphireValue* args);
SapphireValue native_string_starts_with(int arg_count, SapphireValue* args);
SapphireValue native_string_ends_with(int arg_count, SapphireValue* args);
SapphireValue native_string_index_of(int arg_count, SapphireValue* args);
SapphireValue native_string_last_index_of(int arg_count, SapphireValue* args);
SapphireValue native_string_char_at(int arg_count, SapphireValue* args);
SapphireValue native_string_length(int arg_count, SapphireValue* args);
SapphireValue native_string_substring(int arg_count, SapphireValue* args);
SapphireValue native_string_split(int arg_count, SapphireValue* args);
SapphireValue native_string_replace(int arg_count, SapphireValue* args);
SapphireValue native_string_to_upper(int arg_count, SapphireValue* args);
SapphireValue native_string_to_lower(int arg_count, SapphireValue* args);
SapphireValue native_string_trim(int arg_count, SapphireValue* args);
SapphireValue native_string_contains(int arg_count, SapphireValue* args);
SapphireValue native_string_to_double(int arg_count, SapphireValue* args);
SapphireValue native_logger_info(int arg_count, SapphireValue* args);
SapphireValue native_logger_warn(int arg_count, SapphireValue* args);
SapphireValue native_logger_error(int arg_count, SapphireValue* args);
SapphireValue native_logger_debug(int arg_count, SapphireValue* args);
SapphireValue native_spawn(int arg_count, SapphireValue* args);
SapphireValue native_mutex_new(int arg_count, SapphireValue* args);
SapphireValue native_mutex_lock(int arg_count, SapphireValue* args);
SapphireValue native_mutex_unlock(int arg_count, SapphireValue* args);
SapphireValue native_join(int arg_count, SapphireValue* args);
SapphireValue native_system_core_count(int arg_count, SapphireValue* args);
SapphireValue native_system_sleep(int arg_count, SapphireValue* args);
SapphireValue native_system_exec(int arg_count, SapphireValue* args);
SapphireValue native_system_get_os(int arg_count, SapphireValue* args);
SapphireValue native_system_get_env(int arg_count, SapphireValue* args);
SapphireValue native_system_get_clipboard(int arg_count, SapphireValue* args);
SapphireValue native_ui_button(int arg_count, SapphireValue* args);;
SapphireValue native_ui_text(int arg_count, SapphireValue* args);;
SapphireValue native_ui_display(int arg_count, SapphireValue* args);;
SapphireValue native_ui_flex(int arg_count, SapphireValue* args);;
SapphireValue native_ui_checkbox(int arg_count, SapphireValue* args);;
SapphireValue native_ui_slider(int arg_count, SapphireValue* args);;
SapphireValue native_ui_input(int arg_count, SapphireValue* args);;
SapphireValue native_ui_separator(int arg_count, SapphireValue* args);;
SapphireValue native_ui_menu(int arg_count, SapphireValue* args);;
SapphireValue native_ui_menuitem(int arg_count, SapphireValue* args);;
SapphireValue native_ui_grid(int arg_count, SapphireValue* args);;
SapphireValue native_ui_stackpanel(int arg_count, SapphireValue* args);;
SapphireValue native_ui_dockpanel(int arg_count, SapphireValue* args);;
SapphireValue native_ui_wrappanel(int arg_count, SapphireValue* args);;
SapphireValue native_ui_scrollview(int arg_count, SapphireValue* args);;
SapphireValue native_ui_border(int arg_count, SapphireValue* args);;
SapphireValue native_ui_image(int arg_count, SapphireValue* args);;
SapphireValue native_ui_progressbar(int arg_count, SapphireValue* args);;
SapphireValue native_ui_radiobox(int arg_count, SapphireValue* args);;
SapphireValue native_ui_toggleswitch(int arg_count, SapphireValue* args);;
SapphireValue native_ui_combobox(int arg_count, SapphireValue* args);;
SapphireValue native_ui_listbox(int arg_count, SapphireValue* args);;
SapphireValue native_ui_passwordbox(int arg_count, SapphireValue* args);;
SapphireValue native_ui_hyperlink(int arg_count, SapphireValue* args);;
SapphireValue native_ui_expander(int arg_count, SapphireValue* args);;
SapphireValue native_ui_datagrid(int arg_count, SapphireValue* args);;
SapphireValue native_ui_canvas(int arg_count, SapphireValue* args);;
SapphireValue native_ui_tooltip(int arg_count, SapphireValue* args);;
SapphireValue native_ui_popup(int arg_count, SapphireValue* args);;
SapphireValue native_ui_window(int arg_count, SapphireValue* args);;
SapphireValue native_ui_animate(int arg_count, SapphireValue* args);
SapphireValue native_ui_style(int arg_count, SapphireValue* args);
SapphireValue native_ui_get_input_text(int arg_count, SapphireValue* args);
SapphireValue native_ui_render(int arg_count, SapphireValue* args);
// === NEW v1.0.9 ===
SapphireValue native_ui_card(int arg_count, SapphireValue* args);
SapphireValue native_ui_badge(int arg_count, SapphireValue* args);
SapphireValue native_ui_tag(int arg_count, SapphireValue* args);
SapphireValue native_ui_stepper(int arg_count, SapphireValue* args);
SapphireValue native_ui_spinner(int arg_count, SapphireValue* args);
SapphireValue native_ui_notify(int arg_count, SapphireValue* args);

UIStyle resolve_style(const std::string& nodeId, const std::string& styleName);

SapphireValue clock_native(int arg_count, SapphireValue* args);

SapphireValue assert_native(int arg_count, SapphireValue* args);

SapphireValue io_readline_native(int arg_count, SapphireValue* args);

SapphireValue create_declarative_node(const std::string& type, int arg_count, SapphireValue* args);

std::string valueToStringC(const SapphireValue& val);

SapphireValue native_ui_button(int arg_count, SapphireValue* args);
SapphireValue native_ui_text(int arg_count, SapphireValue* args);
SapphireValue native_ui_display(int arg_count, SapphireValue* args);
SapphireValue native_ui_flex(int arg_count, SapphireValue* args);
SapphireValue native_ui_checkbox(int arg_count, SapphireValue* args);
SapphireValue native_ui_slider(int arg_count, SapphireValue* args);
SapphireValue native_ui_input(int arg_count, SapphireValue* args);
SapphireValue native_ui_separator(int arg_count, SapphireValue* args);
SapphireValue native_ui_menu(int arg_count, SapphireValue* args);
SapphireValue native_ui_menuitem(int arg_count, SapphireValue* args);
SapphireValue native_ui_grid(int arg_count, SapphireValue* args);
SapphireValue native_ui_stackpanel(int arg_count, SapphireValue* args);
SapphireValue native_ui_dockpanel(int arg_count, SapphireValue* args);
SapphireValue native_ui_wrappanel(int arg_count, SapphireValue* args);
SapphireValue native_ui_scrollview(int arg_count, SapphireValue* args);
SapphireValue native_ui_border(int arg_count, SapphireValue* args);
SapphireValue native_ui_image(int arg_count, SapphireValue* args);
SapphireValue native_ui_progressbar(int arg_count, SapphireValue* args);
SapphireValue native_ui_radiobox(int arg_count, SapphireValue* args);
SapphireValue native_ui_toggleswitch(int arg_count, SapphireValue* args);
SapphireValue native_ui_combobox(int arg_count, SapphireValue* args);
SapphireValue native_ui_listbox(int arg_count, SapphireValue* args);
SapphireValue native_ui_passwordbox(int arg_count, SapphireValue* args);
SapphireValue native_ui_hyperlink(int arg_count, SapphireValue* args);
SapphireValue native_ui_expander(int arg_count, SapphireValue* args);
SapphireValue native_ui_datagrid(int arg_count, SapphireValue* args);
SapphireValue native_ui_canvas(int arg_count, SapphireValue* args);
SapphireValue native_ui_tooltip(int arg_count, SapphireValue* args);
SapphireValue native_ui_popup(int arg_count, SapphireValue* args);
SapphireValue native_ui_window(int arg_count, SapphireValue* args);
SapphireValue native_ui_animate(int arg_count, SapphireValue* args);
SapphireValue native_ui_style(int arg_count, SapphireValue* args);
SapphireValue native_ui_get_input_text(int arg_count, SapphireValue* args);
SapphireValue native_ui_render(int arg_count, SapphireValue* args);

SapphireValue clock_native(int arg_count, SapphireValue* args);

SapphireValue assert_native(int arg_count, SapphireValue* args);

SapphireValue io_readline_native(int arg_count, SapphireValue* args);

UIStyle resolve_style(int arg_count, SapphireValue* args);

SapphireValue native_json_parse(int arg_count, SapphireValue* args);

SapphireValue native_json_stringify(int arg_count, SapphireValue* args);

UIStyle resolve_style(const std::string& id, const std::string& styleName = "");
