#ifndef TOPAZ_COMMANDS_CLEAN_HPP
#define TOPAZ_COMMANDS_CLEAN_HPP

#include "core/fs_utils.hpp"
#include <iostream>
#include <filesystem>
#include "termcolor.hpp"

namespace topaz {
namespace commands {

inline int cmd_clean(const std::filesystem::path& working_dir) {
    namespace fs = std::filesystem;
    
    std::cout << termcolor::cyan << termcolor::bold << "Cleaning project artifacts..." << termcolor::reset << std::endl;
    
    int removed = 0;
    
    // Clean build directory
    fs::path build_dir = working_dir / "build";
    if (fs::exists(build_dir)) {
        try {
            fs::remove_all(build_dir);
            std::cout << "  Removed " << build_dir.string() << std::endl;
            removed++;
        } catch(const std::exception& e) {
            std::cerr << termcolor::yellow << "  Failed to remove " << build_dir.string() << ": " << e.what() << termcolor::reset << std::endl;
        }
    }

    // Clean BerylConfig.txt
    fs::path beryl_config = working_dir / "BerylConfig.txt";
    if (fs::exists(beryl_config)) {
        try {
            fs::remove(beryl_config);
            std::cout << "  Removed " << beryl_config.string() << std::endl;
            removed++;
        } catch(...) {}
    }
    
    // Clean potential executables generated by Beryl in the root
    for (const auto& entry : fs::directory_iterator(working_dir)) {
        if (entry.is_regular_file() && entry.path().extension() == ".exe") {
            try {
                fs::remove(entry.path());
                std::cout << "  Removed " << entry.path().string() << std::endl;
                removed++;
            } catch(...) {}
        }
    }

    if (removed == 0) {
        std::cout << termcolor::green << "Nothing to clean." << termcolor::reset << std::endl;
    } else {
        std::cout << termcolor::green << "Cleaned " << removed << " artifacts." << termcolor::reset << std::endl;
    }

    return 0;
}

} // namespace commands
} // namespace topaz

#endif // TOPAZ_COMMANDS_CLEAN_HPP
