#ifndef SAPPHIRE_TOKENS_H
#define SAPPHIRE_TOKENS_H

#include <string>

// Definindo TokenType como enum class (SEM forward declaration aqui, apenas a definição completa)
enum class TokenType {
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT, TOKEN_EQUAL,
    TOKEN_BANG, TOKEN_BANG_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_GREATER, TOKEN_GREATER_EQUAL, TOKEN_LESS, TOKEN_LESS_EQUAL,
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS, // ++, --
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL, TOKEN_SLASH_EQUAL, // +=, -=, *=, /=
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN, TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET, TOKEN_SEMICOLON, TOKEN_COMMA, TOKEN_DOT, TOKEN_COLON,
    TOKEN_PRINT, TOKEN_IF, TOKEN_ELSE, TOKEN_TRUE, TOKEN_FALSE, TOKEN_NIL,
    TOKEN_AND, TOKEN_OR, TOKEN_WHILE, TOKEN_FOR, TOKEN_FUNCTION, TOKEN_RETURN, TOKEN_IMPORT,
    TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,
    TOKEN_INT, TOKEN_BOOL, TOKEN_STRING, TOKEN_DOUBLE, TOKEN_FLOAT, TOKEN_VOID,
    TOKEN_CLASS, TOKEN_THIS, TOKEN_CONST, TOKEN_VAR, TOKEN_ENUM,
    TOKEN_BITWISE_AND, TOKEN_BITWISE_OR, TOKEN_BITWISE_XOR, TOKEN_BITWISE_NOT, TOKEN_LEFT_SHIFT, TOKEN_RIGHT_SHIFT,
    TOKEN_QUESTION, TOKEN_TRY, TOKEN_CATCH, TOKEN_THROW,
    TOKEN_NUMBER, TOKEN_STRING_LITERAL, TOKEN_IDENTIFIER,
    TOKEN_END_OF_FILE, TOKEN_ILLEGAL
};

// A STRUCT TOKEN DEVE VIR IMEDIATAMENTE APÓS A DEFINIÇÃO COMPLETA DO ENUM CLASS
struct Token {
    TokenType type;
    std::string literal;
    int line;
    int column;
    int length;
};

#endif // SAPPHIRE_TOKENS_H