name: CI Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSYS2 (MINGW64)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Configure CMake
      shell: msys2 {0}
      run: cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      shell: msys2 {0}
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test Execute
      shell: msys2 {0}
      run: |
        ./build/sapphire.exe tests/test_syntax.sp
        ./build/sapphire.exe tests/test_loop.sp
        ./build/sapphire.exe tests/test_list.sp
        ./build/sapphire.exe tests/test_math.sp
        ./build/sapphire.exe tests/test_types.sp
        ./build/sapphire.exe tests/test_map.sp
