name: CI Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test Execute
      working-directory: ${{github.workspace}}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./build/Release/sapphire.exe tests/test_syntax.sp
          ./build/Release/sapphire.exe tests/test_loop.sp
          ./build/Release/sapphire.exe tests/test_list.sp
          ./build/Release/sapphire.exe tests/test_math.sp
          ./build/Release/sapphire.exe tests/test_types.sp
          ./build/Release/sapphire.exe tests/test_map.sp
        else
          ./build/sapphire tests/test_syntax.sp
          ./build/sapphire tests/test_loop.sp
          ./build/sapphire tests/test_list.sp
          ./build/sapphire tests/test_math.sp
          ./build/sapphire tests/test_types.sp
          ./build/sapphire tests/test_map.sp
        fi
      shell: bash
